### ISSUE TITLE
Checkpoints for ResNet18 on CIFAR10

### ISSUE THREAD

**Issue by jeromerony** [zhenxingjian/Partial_Distance_Correlation#1]
Hi,

Could it be possible to share the checkpoints for ResNet18 on CIFAR10, corresponding to the first 2 rows of Table 1 ?

Thanks,
Jérôme

**Comment by zhenxingjian** [comment]
Hi,
The motherboard of the PC that we used to train these models has broken about 3 months ago. The disks should be fine, but we may need some time to figure that out.
I'll upload the cifar model once we recover the disks from that PC. 
In the meanwhile, maybe you can train the cifar model on your own?
We trained total of 3 models, the first one is trained freely, and the second is independent to the first model, the third is independent to both of the first two models. And we evaluate the attack on the first model and test on the third model.

**Comment by jeromerony** [comment]
Thanks for the quick answer.
It would be difficult to train the models myself, because it seems that you have not provided the script and commands to train the CIFAR10 models.

**Comment by zhenxingjian** [comment]
We uploaded the cifar10 model in the google drive. (https://drive.google.com/drive/folders/1rdrd3RUtLWeATbq1cxmWLqbXLfUhzAc9?usp=sharing)
Also, the attack code is updated to include the cifar10 attack.
Please reach out to us if you have further questions!
