### ISSUE TITLE
Page 6:

### ISSUE THREAD

**Issue by GeryAdhane** [zhenxingjian/Partial_Distance_Correlation#5]
![image](https://user-images.githubusercontent.com/5415564/216083295-d9003609-2ba0-40b8-be1a-10a8bb1daee2.png),
1. is this part highlighted correct, shouldn't Z be Y?
2. Sometimes, a model that has less accuracy score has better representation score. Does this have any valid explanation (if we have to compare the models, which one is a better classifier? the one with better representation score or better better accuracy score)?

thank you.

**Comment by zhenxingjian** [comment]
1. We have to following maps: X->A, Y->B, Z->C, and we are projecting A onto C and only use the remaining. So it would somewhat look like: (X-Z) & Y. Thus, the statement is correct, which answers the question that what is "Remaining" in X when taken out Z.
2. This might come out of that deeper network will focus more on the corner cases and overfit the entire training/testing dataset. And shallower network, though with less accuracy, might focus more on the major pieces, which can have more correlation with the linguistic meanings. This is just my understanding, and it might not be 100% accurate. 


Thanks for being interested into our work.

--
Xingjian
